export enum PlayerAccounts {
    Hiszpan = 'jakubjd',
    Kasix = 'kasix909',
    Niuczesana = 'nieuczeszek',
    Delord = 'pablosabre',
    Nitro = 'nitro69penetrator',
    Fornal = 'tomaszfornal',
    RandomBruces = 'szachowytapir',
    Diables = 'xdiables',
    Netrodal = 'didaskyler',
    Bagieta = 'bagietkaofficial',
    Suchar = 'mokrysucharek',
    Overpow = 'szachowychogath',
    Kubon = 'jakubon000',
    Demonz = 'demonzz1',
}
